// CRAGE Practice Exam · Set 6 · 200 questions across the eleven CRAGE
// modules. Fresh scenarios continuing the same conceptual coverage.
window.QUESTIONS_SET6 = [

// ===== Module 1 · Foundations =====
{ id: 1, topic: "ML Paradigm", correct: "C",
  q: "A streaming platform trains a churn predictor on labelled customer histories. Which paradigm?",
  options: { A: "Reinforcement", B: "Unsupervised", C: "Supervised", D: "Self-supervised" } },
{ id: 2, topic: "ML Paradigm", correct: "B",
  q: "An analyst groups support tickets into themes without pre-existing labels. Which paradigm?",
  options: { A: "Supervised", B: "Unsupervised", C: "Reinforcement", D: "Semi-supervised" } },
{ id: 3, topic: "ML Paradigm", correct: "D",
  q: "A vision team trains by predicting masked patches in unlabelled images. Which paradigm?",
  options: { A: "Supervised", B: "Reinforcement", C: "Unsupervised", D: "Self-supervised" } },
{ id: 4, topic: "ML Paradigm", correct: "A",
  q: "A game AI learns by playing matches and receiving rewards for winning positions. Which paradigm?",
  options: { A: "Reinforcement", B: "Supervised", C: "Self-supervised", D: "Unsupervised" } },
{ id: 5, topic: "Architectures", correct: "C",
  q: "A multilingual summariser processes whole sequences in parallel with self-attention. Which architecture fits?",
  options: { A: "CNN", B: "RNN", C: "Transformer", D: "RBF" } },
{ id: 6, topic: "Architectures", correct: "A",
  q: "A medical-imaging team builds an image classifier with local convolutions and pooling. Which architecture fits?",
  options: { A: "CNN", B: "Transformer", C: "Autoencoder", D: "GAN" } },
{ id: 7, topic: "Architectures", correct: "B",
  q: "A team analyses sensor time-series where the order matters and the model maintains state across steps. Which architecture fits?",
  options: { A: "CNN", B: "RNN", C: "Autoencoder", D: "GAN" } },
{ id: 8, topic: "Architectures", correct: "D",
  q: "A studio synthesises new training images using a generator and discriminator trained adversarially. Which architecture?",
  options: { A: "CNN", B: "Autoencoder", C: "RNN", D: "GAN" } },
{ id: 9, topic: "Generative AI", correct: "B",
  q: "A finance copilot retrieves the latest policy excerpts from a vector store and adds them to the LLM prompt. Which technique?",
  options: { A: "Fine-tuning", B: "Retrieval-Augmented Generation (RAG)", C: "Pre-training", D: "Distillation" } },
{ id: 10, topic: "Generative AI", correct: "A",
  q: "A team specialises a 13B model using small low-rank adapter matrices, base weights frozen. Which technique?",
  options: { A: "LoRA", B: "Quantisation", C: "RAG", D: "Pruning" } },
{ id: 11, topic: "Generative AI", correct: "C",
  q: "Human preference rankings train a reward model that tunes the LLM via policy optimisation. Which technique?",
  options: { A: "Pre-training", B: "Distillation", C: "RLHF", D: "RAG" } },
{ id: 12, topic: "Hardware", correct: "B",
  q: "Custom Google silicon optimised for tensor operations is best classified as a...",
  options: { A: "GPU", B: "TPU", C: "FPGA", D: "Mainframe CPU" } },
{ id: 13, topic: "Hardware", correct: "C",
  q: "A reconfigurable accelerator reprogrammable for different ML workloads after deployment is a...",
  options: { A: "GPU", B: "TPU", C: "FPGA", D: "ASIC" } },
{ id: 14, topic: "Deployment", correct: "D",
  q: "Hearing-aid runs ML inference on-device with no cloud round-trip. Which pattern?",
  options: { A: "Cloud inference", B: "Federated learning", C: "Serverless", D: "Edge / on-device" } },
{ id: 15, topic: "AI Stack", correct: "B",
  q: "A vendor sells an embedding service plus managed vector index used for RAG. Which layer?",
  options: { A: "Foundation model", B: "Retrieval (RAG) layer", C: "Fine-tuning service", D: "MLOps" } },
{ id: 16, topic: "AI Stack", correct: "A",
  q: "A vendor offers a service to assemble multi-step LLM agent workflows with tool calls, planners, memory. Which layer?",
  options: { A: "Agent / orchestration layer", B: "Foundation model", C: "Retrieval", D: "Hardware" } },
{ id: 17, topic: "Foundation Models", correct: "C",
  q: "A model 'pre-trained on broad data at scale, adaptable to many downstream tasks via fine-tuning or prompting' is called a...",
  options: { A: "Edge model", B: "Specialist model", C: "Foundation model", D: "Federated model" } },
{ id: 18, topic: "Documentation", correct: "B",
  q: "Before deploying an in-house LLM, a structured artefact covers architecture, intended use, factors, metrics, training data, eval data, ethics, limitations, license. What is this?",
  options: { A: "Datasheet", B: "Model card", C: "Decision log", D: "AIBOM" } },

// ===== Module 2 · Ethics =====
{ id: 19, topic: "OECD Principles", correct: "A",
  q: "Which OECD principle promotes inclusive growth, sustainable development and well-being while reducing inequality?",
  options: { A: "Inclusive growth", B: "Robustness", C: "Accountability", D: "Transparency" } },
{ id: 20, topic: "OECD Principles", correct: "C",
  q: "Which OECD principle requires AI designers/operators to be answerable for proper functioning?",
  options: { A: "Transparency", B: "Inclusive growth", C: "Accountability", D: "Robustness" } },
{ id: 21, topic: "OECD Principles", correct: "D",
  q: "Which OECD principle requires AI to function in a robust, secure and safe way throughout its lifecycle?",
  options: { A: "Inclusive growth", B: "Accountability", C: "Transparency", D: "Robustness, security and safety" } },
{ id: 22, topic: "OECD Principles", correct: "B",
  q: "Which OECD principle requires meaningful information so those affected can understand and challenge AI outcomes?",
  options: { A: "Inclusive growth", B: "Transparency and explainability", C: "Accountability", D: "Robustness" } },
{ id: 23, topic: "OECD Principles", correct: "A",
  q: "Which OECD principle requires AI respect rule of law, human rights, democratic values, with safeguards (e.g. human determination)?",
  options: { A: "Human-centered values and fairness", B: "Inclusive growth", C: "Accountability", D: "Robustness" } },
{ id: 24, topic: "Fairness Metrics", correct: "B",
  q: "Predicted positive rate equal across groups. Which fairness metric?",
  options: { A: "Equalized odds", B: "Statistical parity", C: "Calibration", D: "Equality of opportunity" } },
{ id: 25, topic: "Fairness Metrics", correct: "A",
  q: "Recall equal across groups among truly positive cases. Which fairness metric?",
  options: { A: "Equality of opportunity", B: "Statistical parity", C: "Calibration", D: "Predictive parity" } },
{ id: 26, topic: "Fairness Metrics", correct: "C",
  q: "TPR and FPR both equal across groups. Which fairness metric?",
  options: { A: "Statistical parity", B: "Calibration", C: "Equalized odds", D: "Counterfactual fairness" } },
{ id: 27, topic: "Fairness Metrics", correct: "D",
  q: "At any predicted score, actual outcome rates match across groups. Which fairness metric?",
  options: { A: "Statistical parity", B: "Equalized odds", C: "Equality of opportunity", D: "Calibration" } },
{ id: 28, topic: "Bias Types", correct: "C",
  q: "Training data over-represents one demographic; underperformance on minorities. Which bias type?",
  options: { A: "Algorithmic", B: "Historical", C: "Sampling", D: "Confirmation" } },
{ id: 29, topic: "Bias Types", correct: "B",
  q: "Historical lending discrimination reproduced because training data reflects past decisions. Which bias type?",
  options: { A: "Algorithmic", B: "Historical / societal", C: "Sampling", D: "Label" } },
{ id: 30, topic: "Bias Types", correct: "A",
  q: "Optimisation favours feature combinations producing disparate impact, even with balanced inputs. Which bias type?",
  options: { A: "Algorithmic", B: "Data", C: "Sampling", D: "Label noise" } },
{ id: 31, topic: "Bias Types", correct: "D",
  q: "Annotators applied different criteria, producing inconsistent labels. Which bias type?",
  options: { A: "Algorithmic", B: "Sampling", C: "Historical", D: "Label" } },
{ id: 32, topic: "Trustworthy AI", correct: "C",
  q: "Which NIST trustworthy-AI characteristic refers to 'fair with harmful bias managed'?",
  options: { A: "Privacy-enhanced", B: "Accountable", C: "Fair", D: "Explainable" } },
{ id: 33, topic: "Human Oversight", correct: "B",
  q: "EU AI Act obligation: high-risk AI designed so persons can effectively oversee, intervene, stop. Called...",
  options: { A: "Conformity assessment", B: "Human oversight", C: "Post-market monitoring", D: "Risk management system" } },
{ id: 34, topic: "Explainability", correct: "C",
  q: "XAI technique generating a local linear approximation around a prediction. Which?",
  options: { A: "SHAP", B: "Anchors", C: "LIME", D: "Counterfactual" } },
{ id: 35, topic: "Explainability", correct: "A",
  q: "XAI technique attributing predictions to features via Shapley values across coalitions. Which?",
  options: { A: "SHAP", B: "LIME", C: "Saliency", D: "Anchors" } },
{ id: 36, topic: "Explainability", correct: "B",
  q: "XAI 'what if' explanation: 'if income were higher, approval would have followed'. Which technique?",
  options: { A: "LIME", B: "Counterfactual explanation", C: "SHAP", D: "Anchors" } },

// ===== Module 3 · Strategy =====
{ id: 37, topic: "Sourcing", correct: "B",
  q: "Unique proprietary data + deep expertise + strategic moat. Which sourcing strategy?",
  options: { A: "Buy", B: "Build", C: "Partner", D: "Outsource" } },
{ id: 38, topic: "Sourcing", correct: "A",
  q: "Commodity AI use case + tight delivery + no differentiation. Which sourcing strategy?",
  options: { A: "Buy", B: "Build", C: "DIY", D: "Outsource" } },
{ id: 39, topic: "Sourcing", correct: "C",
  q: "Vendor's mature model + your proprietary data; both contribute IP. Which sourcing strategy?",
  options: { A: "Buy", B: "Build", C: "Partner / co-develop", D: "Outsource" } },
{ id: 40, topic: "Business Case", correct: "D",
  q: "Reviewing whether expected value exceeds lifecycle cost. Which element?",
  options: { A: "Strategic Alignment", B: "Risk Assessment", C: "Implementation Roadmap", D: "ROI / NPV" } },
{ id: 41, topic: "Business Case", correct: "A",
  q: "Reviewing whether a proposal advances the org's published strategy. Which element?",
  options: { A: "Strategic Alignment", B: "ROI", C: "Risk Assessment", D: "Implementation Roadmap" } },
{ id: 42, topic: "Cost Mgmt", correct: "B",
  q: "Before scaling, finance enumerates every recurring cost across compute, storage, fine-tuning, monitoring, retraining, fees. Which step?",
  options: { A: "Budget allocation", B: "Cost component identification", C: "Spend prioritisation", D: "Cost-benefit analysis" } },
{ id: 43, topic: "Capability Gap", correct: "C",
  q: "Six AI initiatives in flight, no shared platform, drift undetected for weeks. Which next hire?",
  options: { A: "Junior data scientist", B: "Prompt engineer", C: "ML platform lead", D: "Foundation researcher" } },
{ id: 44, topic: "Pilot Evaluation", correct: "A",
  q: "Quantitative metrics meet threshold but operators report friction. Leadership concludes system needs iteration. Which interpretation?",
  options: { A: "Refinement needs", B: "Scale recommendation", C: "Fail-fast", D: "Success indicators" } },
{ id: 45, topic: "Use Case Prioritisation", correct: "D",
  q: "Initiatives placed on value-vs-risk grid then sequenced by quadrant. Which framework?",
  options: { A: "RACI", B: "MoSCoW", C: "FMEA", D: "Value-Risk matrix" } },
{ id: 46, topic: "Strategy", correct: "A",
  q: "Exec board approves an org-wide document defining priorities, alignment, governance, long-term direction. Which decision category?",
  options: { A: "AI strategy", B: "AI project plan", C: "AI pilot list", D: "AI hiring plan" } },
{ id: 47, topic: "Maturity", correct: "B",
  q: "Assessment characterises an org along exploratory, experimental, formalised, optimised, transformational. What kind of model?",
  options: { A: "Risk register", B: "AI maturity model", C: "Compliance framework", D: "Cost model" } },
{ id: 48, topic: "Sourcing Decision", correct: "D",
  q: "Build-buy-partner framework. Most foundational factor?",
  options: { A: "Vendor logo", B: "Engineer language preferences", C: "Office snacks", D: "Strategic value, time-to-market, capability fit, risk profile" } },

// ===== Module 4 · Governance =====
{ id: 49, topic: "NIST AI RMF", correct: "B",
  q: "Which NIST AI RMF function focuses on context, intended use, foreseeable misuse, impact?",
  options: { A: "GOVERN", B: "MAP", C: "MEASURE", D: "MANAGE" } },
{ id: 50, topic: "NIST AI RMF", correct: "C",
  q: "Which NIST AI RMF function focuses on metrics, evals, monitoring, audit?",
  options: { A: "GOVERN", B: "MAP", C: "MEASURE", D: "MANAGE" } },
{ id: 51, topic: "NIST AI RMF", correct: "A",
  q: "Which NIST AI RMF function cuts across the others — culture, policy, accountability, integration?",
  options: { A: "GOVERN", B: "MAP", C: "MEASURE", D: "MANAGE" } },
{ id: 52, topic: "NIST AI RMF", correct: "D",
  q: "Which NIST AI RMF function focuses on prioritising, responding to, improving identified risks throughout the lifecycle?",
  options: { A: "GOVERN", B: "MAP", C: "MEASURE", D: "MANAGE" } },
{ id: 53, topic: "ISO/IEC 42001", correct: "C",
  q: "Which ISO/IEC 42001 clause requires AI system impact assessment addressing effects on individuals, groups, society?",
  options: { A: "Clause 4", B: "Clause 6.1.2", C: "Clause 8.3", D: "Clause 9.2" } },
{ id: 54, topic: "ISO/IEC 42001", correct: "B",
  q: "Which ISO/IEC 42001 clause defines internal/external issues, interested parties, AIMS scope?",
  options: { A: "Clause 5", B: "Clause 4 — Context", C: "Clause 6", D: "Clause 8" } },
{ id: 55, topic: "ISO/IEC 42001", correct: "D",
  q: "Which ISO/IEC 42001 clause covers internal audit of the AIMS?",
  options: { A: "Clause 4", B: "Clause 6", C: "Clause 8", D: "Clause 9.2" } },
{ id: 56, topic: "ISO Standards", correct: "C",
  q: "Which ISO standard provides AI-specific risk management guidance complementing ISO 31000?",
  options: { A: "ISO 27001", B: "ISO 9001", C: "ISO/IEC 23894", D: "ISO 21434" } },
{ id: 57, topic: "Governance Models", correct: "A",
  q: "Regulator expects clear lines of authority spanning all business units with consistent enterprise enforcement. Which model?",
  options: { A: "Centralized", B: "Federated", C: "DAO", D: "Outsourced" } },
{ id: 58, topic: "Governance Models", correct: "B",
  q: "Multinational with diverse local contexts retaining business-line discretion under common central standards. Which model?",
  options: { A: "Centralized", B: "Federated", C: "Hybrid", D: "DAO" } },
{ id: 59, topic: "Governance Models", correct: "C",
  q: "Central AI governance office owns policy; local ML teams own execution. Which model?",
  options: { A: "Centralized", B: "Federated", C: "Hybrid", D: "DAO" } },
{ id: 60, topic: "Roles", correct: "A",
  q: "Single accountable executive for AI portfolio — strategy, risk, positioning — is most appropriately the...",
  options: { A: "Chief AI Officer", B: "CMO", C: "VP Engineering", D: "Chief Architect" } },
{ id: 61, topic: "Roles", correct: "C",
  q: "Role responsible for personal-data processing review, DPIAs, DPA engagement is the...",
  options: { A: "CISO", B: "CFO", C: "Data Protection Officer", D: "Engineering Manager" } },
{ id: 62, topic: "Roles", correct: "B",
  q: "Continuity and internal coherence of model components across releases belongs to which role?",
  options: { A: "Business owner", B: "Model custodian", C: "Marketing lead", D: "AIOps junior" } },
{ id: 63, topic: "Governance Bodies", correct: "D",
  q: "Strategic risk-appetite decisions translated into coordinated org-wide guidance for consistent execution. Which body?",
  options: { A: "Working group", B: "Ethics panel", C: "Engineering guild", D: "Steering committee" } },
{ id: 64, topic: "Governance Bodies", correct: "A",
  q: "Internal body evaluating AI initiatives early, arbitrating innovation vs ethics, giving ethical guidance. Which body?",
  options: { A: "Company AI Ethics Board", B: "Risk committee", C: "Audit committee", D: "Steering committee" } },
{ id: 65, topic: "RACI", correct: "B",
  q: "Why exactly one role marked 'A' in a high-risk AI launch RACI?",
  options: { A: "RACI doesn't constrain A's", B: "Accountability is singular; two A's mean nobody is accountable", C: "Two A's share blame", D: "A is optional" } },
{ id: 66, topic: "EU AI Office", correct: "B",
  q: "Under the EU AI Act, which Commission body oversees implementation especially for general-purpose AI models?",
  options: { A: "EDPB", B: "European AI Office", C: "ENISA", D: "ECJ" } },

// ===== Module 5 · Compliance =====
{ id: 67, topic: "EU AI Act Tiers", correct: "C",
  q: "AI chatbot for EU consumers must clearly disclose AI to users. Which tier?",
  options: { A: "Prohibited", B: "High-risk", C: "Limited-risk", D: "Minimal-risk" } },
{ id: 68, topic: "EU AI Act Tiers", correct: "A",
  q: "Real-time biometric identification for general law-enforcement surveillance in public. Which tier?",
  options: { A: "Prohibited", B: "High-risk", C: "Limited-risk", D: "Minimal-risk" } },
{ id: 69, topic: "EU AI Act Tiers", correct: "B",
  q: "EU bank deploys AI for creditworthiness assessment of natural persons. Which tier?",
  options: { A: "Prohibited", B: "High-risk", C: "Limited-risk", D: "Minimal-risk" } },
{ id: 70, topic: "EU AI Act Tiers", correct: "D",
  q: "AI-powered video-game NPC adapts based on player input. Which tier?",
  options: { A: "Prohibited", B: "High-risk", C: "Limited-risk", D: "Minimal-risk" } },
{ id: 71, topic: "EU AI Act Obligations", correct: "C",
  q: "Before placing a high-risk AI system on the EU market, providers must complete which procedure?",
  options: { A: "Penetration test", B: "OECD self-assessment", C: "Conformity assessment + EU declaration of conformity", D: "Customer survey" } },
{ id: 72, topic: "GDPR", correct: "B",
  q: "Which GDPR article governs solely-automated decisions with legal effect and grants right to human intervention?",
  options: { A: "Article 5", B: "Article 22", C: "Article 17", D: "Article 33" } },
{ id: 73, topic: "GDPR", correct: "A",
  q: "Which GDPR article requires a DPIA when processing is likely to result in high risk?",
  options: { A: "Article 35", B: "Article 22", C: "Article 25", D: "Article 6" } },
{ id: 74, topic: "GDPR", correct: "C",
  q: "Which GDPR principle requires data collected for specified, legitimate purposes — not further processed in incompatible ways?",
  options: { A: "Lawfulness", B: "Data minimisation", C: "Purpose limitation", D: "Accuracy" } },
{ id: 75, topic: "GDPR", correct: "D",
  q: "Which GDPR right allows the data subject to receive their data in a structured machine-readable format?",
  options: { A: "Right to access", B: "Right to erasure", C: "Right to object", D: "Right to data portability" } },
{ id: 76, topic: "GDPR", correct: "A",
  q: "Article 25 codifies which two operational privacy principles?",
  options: { A: "Data protection by design and by default", B: "Lawfulness and accuracy", C: "Storage limitation and accuracy", D: "Consent and legitimate interest" } },
{ id: 77, topic: "US Sectoral", correct: "B",
  q: "US healthcare provider engages AI vendor that will receive PHI. Which contract required by HIPAA?",
  options: { A: "DPA", B: "BAA", C: "MSA only", D: "SOC 2" } },
{ id: 78, topic: "US Sectoral", correct: "C",
  q: "Fed SR 11-7 supervisory guidance requires which combination?",
  options: { A: "Pen test only", B: "External marketing reviews", C: "Effective challenge, governance, development controls, validation, ongoing monitoring", D: "Quarterly board surveys" } },
{ id: 79, topic: "US Sectoral", correct: "D",
  q: "Adverse-action notice with specific reasons when AI denies credit. Which law?",
  options: { A: "TCPA", B: "GLBA", C: "HIPAA", D: "FCRA" } },
{ id: 80, topic: "US Sectoral", correct: "A",
  q: "AI-generated voices in outbound calls to US consumers regulated as robocalls by which regulator?",
  options: { A: "FCC", B: "SEC", C: "FAA", D: "FTC alone" } },
{ id: 81, topic: "US Sectoral", correct: "B",
  q: "AI for medical diagnosis or monitoring without being part of a hardware device falls under which framework?",
  options: { A: "HIPAA only", B: "FDA Software as a Medical Device (SaMD)", C: "OSHA", D: "21 CFR 11" } },
{ id: 82, topic: "International", correct: "C",
  q: "Chinese subsidiary chatbot processing data of users in China primarily falls under which framework?",
  options: { A: "GDPR", B: "CCPA", C: "PIPL", D: "DPDP Act" } },
{ id: 83, topic: "International", correct: "D",
  q: "AI vendor serving Brazilian customers must primarily comply with which national law?",
  options: { A: "GDPR", B: "PIPL", C: "POPIA", D: "LGPD" } },
{ id: 84, topic: "International", correct: "B",
  q: "AI vendor serving consumers in India primarily complies with which law?",
  options: { A: "GDPR", B: "DPDP Act 2023", C: "PIPL", D: "LGPD" } },
{ id: 85, topic: "EU NIS2", correct: "A",
  q: "EU critical-infrastructure operator: incident reporting and risk management obligations under which directive?",
  options: { A: "NIS2", B: "GDPR", C: "ePrivacy", D: "PSD2" } },
{ id: 86, topic: "EU DORA", correct: "B",
  q: "EU financial entity using third-party AI: ICT risk and incident reporting under which regulation?",
  options: { A: "MiFID II", B: "DORA", C: "EMIR", D: "AIFMD" } },

// ===== Module 6 · Risk =====
{ id: 87, topic: "Risk Methodology", correct: "B",
  q: "Team lists failure modes scoring severity, occurrence, detectability; synthesises an RPN. Which technique?",
  options: { A: "Bow-tie", B: "FMEA", C: "Monte Carlo", D: "STRIDE" } },
{ id: 88, topic: "Risk Methodology", correct: "A",
  q: "Single failure event in centre, prevention controls left, impact-reduction right. Which technique?",
  options: { A: "Bow-tie", B: "FMEA", C: "STRIDE", D: "PASTA" } },
{ id: 89, topic: "Risk Methodology", correct: "C",
  q: "Thousands of randomised simulations across uncertain inputs to estimate outcome distribution. Which technique?",
  options: { A: "FMEA", B: "Bow-tie", C: "Monte Carlo simulation", D: "Scenario analysis" } },
{ id: 90, topic: "Risk Methodology", correct: "D",
  q: "Systematically explore credible-but-non-observed conditions: degraded inputs, disrupted dependencies. Which technique?",
  options: { A: "Quantitative scoring", B: "Historical analysis", C: "Threat modelling", D: "Scenario analysis" } },
{ id: 91, topic: "RPN", correct: "B",
  q: "RPN computed by multiplying which three?",
  options: { A: "Cost × probability × time", B: "Severity × occurrence × detectability", C: "Likelihood × impact × velocity", D: "Severity × frequency × revenue" } },
{ id: 92, topic: "Risk Treatment", correct: "C",
  q: "Decision not to deploy at all because residual risk after controls remains unacceptable. Which option?",
  options: { A: "Acceptance", B: "Mitigation", C: "Avoidance", D: "Transfer" } },
{ id: 93, topic: "Risk Treatment", correct: "B",
  q: "Buying cybersecurity insurance against a potential AI breach. Which option?",
  options: { A: "Acceptance", B: "Transfer", C: "Avoidance", D: "Mitigation" } },
{ id: 94, topic: "Risk Treatment", correct: "A",
  q: "Board lives with residual risk because further mitigation isn't worth the cost. Which option?",
  options: { A: "Acceptance", B: "Avoidance", C: "Transfer", D: "Monitoring" } },
{ id: 95, topic: "MITRE ATLAS", correct: "B",
  q: "Attacker probes AI API to fingerprint the underlying model architecture. Which ATLAS tactic?",
  options: { A: "Initial access", B: "Reconnaissance", C: "Execution", D: "Exfiltration" } },
{ id: 96, topic: "MITRE ATLAS", correct: "C",
  q: "Attacker injects malicious instruction in a retrieved web page that the LLM treats as authoritative. Which ATLAS tactic?",
  options: { A: "Reconnaissance", B: "Initial access", C: "Execution (prompt injection)", D: "Persistence" } },
{ id: 97, topic: "MITRE ATLAS", correct: "D",
  q: "Months of crafted queries reconstruct another customer's profile. Which ATLAS tactic?",
  options: { A: "Reconnaissance", B: "Initial access", C: "Execution", D: "Exfiltration" } },
{ id: 98, topic: "AI Attacks", correct: "A",
  q: "Attacker submits crafted training samples to a crowdsourced pipeline so the model contains a backdoor. Which attack?",
  options: { A: "Data poisoning", B: "Model stealing", C: "Membership inference", D: "Adversarial evasion" } },
{ id: 99, topic: "AI Attacks", correct: "B",
  q: "Thousands of queries to determine whether a specific record was in training. Which attack?",
  options: { A: "Model inversion", B: "Membership inference", C: "Model stealing", D: "Adversarial evasion" } },
{ id: 100, topic: "AI Attacks", correct: "C",
  q: "Extensive structured querying for months; competitors then ship near-identical decisions. Which attack?",
  options: { A: "Membership inference", B: "Adversarial evasion", C: "Model stealing", D: "Supply chain compromise" } },
{ id: 101, topic: "AI Attacks", correct: "D",
  q: "Attacker exploits outputs to reconstruct sensitive training inputs (e.g. faces). Which attack?",
  options: { A: "Membership inference", B: "Model stealing", C: "Adversarial evasion", D: "Model inversion" } },
{ id: 102, topic: "AI Attacks", correct: "A",
  q: "Crafted inputs lie just inside a decision boundary to bypass detection at inference. Which attack?",
  options: { A: "Adversarial evasion", B: "Data poisoning", C: "Model stealing", D: "Supply chain compromise" } },
{ id: 103, topic: "Threat Modelling", correct: "C",
  q: "Categories: Spoofing, Tampering, Repudiation, Info disclosure, DoS, Elevation. Which framework?",
  options: { A: "PASTA", B: "OCTAVE", C: "STRIDE", D: "TRIKE" } },
{ id: 104, topic: "Threat Modelling", correct: "B",
  q: "Privacy framework with Linkability, Identifiability, Non-repudiation, Detectability, Disclosure, Unawareness, Non-compliance. Which framework?",
  options: { A: "STRIDE", B: "LINDDUN", C: "PASTA", D: "DREAD" } },
{ id: 105, topic: "Drift Types", correct: "A",
  q: "Input distribution changed (demographics shift) but input-output relationship hasn't. Which drift type?",
  options: { A: "Covariate / data drift", B: "Concept drift", C: "Prior probability drift", D: "Label drift" } },
{ id: 106, topic: "Drift Types", correct: "B",
  q: "What 'fraud' looks like is genuinely different now than at training time. Which drift type?",
  options: { A: "Covariate drift", B: "Concept drift", C: "Prior probability drift", D: "Sampling drift" } },

// ===== Module 7 · TPRM =====
{ id: 107, topic: "TPRM Lifecycle", correct: "A",
  q: "First TPRM step before any risk assessment: establish visibility into which vendors are involved. Which step?",
  options: { A: "Identification and mapping", B: "Due diligence", C: "Contractual controls", D: "Continuous monitoring" } },
{ id: 108, topic: "TPRM Lifecycle", correct: "B",
  q: "Structured evaluation of vendor technical maturity, governance, ethics, security, regulatory readiness. Which step?",
  options: { A: "Identification", B: "Vendor due diligence", C: "Onboarding", D: "Exit planning" } },
{ id: 109, topic: "TPRM Lifecycle", correct: "C",
  q: "Formalising uptime, IP terms, DPAs, incident SLAs in the agreement. Which step?",
  options: { A: "Identification", B: "Due diligence", C: "Contractual controls", D: "Continuous monitoring" } },
{ id: 110, topic: "TPRM Lifecycle", correct: "D",
  q: "Maintaining post-onboarding visibility into vendor obligations and risks. Which step?",
  options: { A: "Identification", B: "Due diligence", C: "Contracting", D: "Continuous monitoring" } },
{ id: 111, topic: "Vendor Contracts", correct: "B",
  q: "Vendor agreement: process personal data only for authorised purposes, assist with subject rights, no sub-processors without consent. Which contract type?",
  options: { A: "MSA", B: "DPA", C: "BAA", D: "License agreement" } },
{ id: 112, topic: "Vendor Contracts", correct: "C",
  q: "SLA: 99.9% uptime, response <1h, resolution <8h, service credits if missed. These are best described as...",
  options: { A: "Internal goals", B: "Best-effort targets", C: "Externally enforceable obligations", D: "Marketing language" } },
{ id: 113, topic: "Vendor Contracts", correct: "D",
  q: "US healthcare provider engaging vendor that will receive PHI requires which contract under HIPAA?",
  options: { A: "DPA", B: "MSA", C: "Standard SaaS agreement", D: "Business Associate Agreement (BAA)" } },
{ id: 114, topic: "Vendor Assurance", correct: "A",
  q: "SOC 2 Type II preferred over Type I because...",
  options: { A: "Type II tests operating effectiveness over time; Type I is point-in-time", B: "Type II is cheaper", C: "Type I covers more controls", D: "Equivalent" } },
{ id: 115, topic: "Third-Party Roles", correct: "B",
  q: "Provider delivers elastic compute, storage, security, managed ML platform; customer retains app logic. Which role?",
  options: { A: "AI-as-a-Service", B: "Cloud provider", C: "Model provider", D: "Data vendor" } },
{ id: 116, topic: "Third-Party Roles", correct: "C",
  q: "Provider exposes foundation-model capabilities only via managed API; customers never see weights. Which role?",
  options: { A: "Cloud provider", B: "Model provider", C: "AI-as-a-Service (API)", D: "Data vendor" } },
{ id: 117, topic: "Third-Party Roles", correct: "D",
  q: "Vendor licenses pre-trained weights for customers to fine-tune and serve in their own environment. Which role?",
  options: { A: "Cloud provider", B: "Data vendor", C: "AI-as-a-Service", D: "Model provider" } },
{ id: 118, topic: "Licenses", correct: "A",
  q: "Bundling CC-BY-NC-4.0 weights in a commercial product. Assessment?",
  options: { A: "Blocked — non-commercial", B: "Permitted with attribution", C: "Permitted under fair use", D: "Permitted with copyleft" } },
{ id: 119, topic: "Licenses", correct: "B",
  q: "Bundling Apache-2.0 library in a commercial AI product primarily requires...",
  options: { A: "Release under GPL", B: "Preserve NOTICE and attribution", C: "Per-seat fee", D: "Non-commercial only" } },
{ id: 120, topic: "Licenses", correct: "C",
  q: "Embedding GPL-3.0 in closed-source commercial AI typically requires...",
  options: { A: "No action", B: "Attribution only", C: "Release source under GPL-compatible terms", D: "Annual royalty" } },
{ id: 121, topic: "Vendor Failures", correct: "B",
  q: "Vendor used customer data beyond agreed purpose, shared with third parties, processed in unauthorised ways. Which failure?",
  options: { A: "Biased decision logic", B: "Unauthorized secondary data use", C: "Poor data quality", D: "Unreliable output" } },
{ id: 122, topic: "Procurement", correct: "B",
  q: "Vendor evaluation emphasising confidentiality, integrity, resilience across lifecycle. Which criterion?",
  options: { A: "Vendor reputation", B: "Security and data privacy measures", C: "Pricing flexibility", D: "Data localisation" } },
{ id: 123, topic: "Procurement", correct: "B",
  q: "Vendor shortlisted on demos and references; bias discovered only after contracts signed. Which stage went wrong?",
  options: { A: "Identify potential vendors", B: "Conduct risk & technical evaluations", C: "Negotiate contracts", D: "Continuous monitoring" } },

// ===== Module 8 · Security =====
{ id: 124, topic: "Defence", correct: "A",
  q: "Successive controls so a single compromise doesn't grant unrestricted downstream access. Which principle?",
  options: { A: "Defence in depth", B: "Least privilege", C: "Open by default", D: "Need-to-know" } },
{ id: 125, topic: "Defence", correct: "B",
  q: "Each service account is granted only the minimum permissions for its task. Which principle?",
  options: { A: "Defence in depth", B: "Least privilege", C: "Open by default", D: "Network trust" } },
{ id: 126, topic: "Defence", correct: "D",
  q: "Network access never implicitly trusted; every request authenticated and continuously validated. Which model?",
  options: { A: "DMZ", B: "Implicit trust", C: "Perimeter security", D: "Zero trust" } },
{ id: 127, topic: "Architecture", correct: "C",
  q: "Isolating ingestion, training, inference into separate network segments after lateral-movement breach. Which principle?",
  options: { A: "Microservices", B: "Containerisation", C: "Network segmentation", D: "Tokenisation" } },
{ id: 128, topic: "Architecture", correct: "D",
  q: "Workload packaged with dependencies in a lightweight image, with image signing and SBOM. Which approach?",
  options: { A: "Bare-metal", B: "Virtualisation only", C: "Serverless", D: "Containerisation" } },
{ id: 129, topic: "Authorisation", correct: "A",
  q: "Junior agent attempts admin-only refund tool; blocked because assigned role lacks permission. Which control?",
  options: { A: "RBAC", B: "Rate limiting", C: "Output filter", D: "Encryption at rest" } },
{ id: 130, topic: "Authorisation", correct: "B",
  q: "Access granted when subject, resource, and context attributes match policy. Which model?",
  options: { A: "RBAC", B: "ABAC", C: "MAC", D: "DAC" } },
{ id: 131, topic: "Controls", correct: "C",
  q: "Multi-tenant LLM platform restricts API calls per key in a sliding window. Which control?",
  options: { A: "Segmentation", B: "Load balancing", C: "Rate limiting", D: "Encryption" } },
{ id: 132, topic: "Controls", correct: "D",
  q: "Layer detects and blocks jailbreak attempts in user input before reaching the model. Which control?",
  options: { A: "Output DLP", B: "Encryption at rest", C: "RBAC", D: "Input filter / prompt firewall" } },
{ id: 133, topic: "Controls", correct: "B",
  q: "LLM reply inspected downstream; PII redacted before reaching user. Which control?",
  options: { A: "Input filter", B: "Output filter / DLP", C: "Containerisation", D: "Network segmentation" } },
{ id: 134, topic: "Controls", correct: "A",
  q: "Autonomous agent must get human approval for refunds over $500. Which control?",
  options: { A: "Human-in-loop action approval", B: "Rate limit", C: "TLS", D: "Encryption" } },
{ id: 135, topic: "Supply Chain", correct: "C",
  q: "Each model artefact signed by its publisher; consumers verify signature and SHA-256 before deployment. Which control?",
  options: { A: "Tokenisation", B: "Rate limiting", C: "Model signing / cryptographic verification", D: "DPA" } },
{ id: 136, topic: "Supply Chain", correct: "B",
  q: "SBOM-style document enumerating every model component, dataset, dependency. Commonly called...",
  options: { A: "EULA", B: "AIBOM", C: "AUP", D: "DPA" } },
{ id: 137, topic: "Vulnerability Mgmt", correct: "B",
  q: "Triaging newly discovered vulnerabilities by exploitability, impact, blast radius. Which step?",
  options: { A: "Identification", B: "Assessment", C: "Mitigation", D: "Monitoring" } },
{ id: 138, topic: "NIST CSF", correct: "A",
  q: "Which NIST CSF function develops org understanding to manage cybersecurity risk?",
  options: { A: "Identify", B: "Protect", C: "Detect", D: "Respond" } },
{ id: 139, topic: "NIST CSF", correct: "C",
  q: "Which NIST CSF function develops activities to identify the occurrence of a cybersecurity event?",
  options: { A: "Identify", B: "Protect", C: "Detect", D: "Recover" } },
{ id: 140, topic: "NIST CSF", correct: "D",
  q: "Which NIST CSF function maintains resilience plans and restores capabilities after an incident?",
  options: { A: "Identify", B: "Detect", C: "Respond", D: "Recover" } },
{ id: 141, topic: "Development", correct: "B",
  q: "Architecture review, threat modelling, SAST, vuln testing embedded in every project phase. Which approach?",
  options: { A: "Continuous Deployment", B: "Secure SDLC", C: "RAD", D: "Marketing-led" } },
{ id: 142, topic: "Frameworks", correct: "C",
  q: "Framework covering identify/protect/detect/respond/recover for AI models, data, infra. Which?",
  options: { A: "MITRE ATLAS", B: "OWASP Top 10 for LLMs", C: "NIST CSF", D: "ISO 27001 controls only" } },
{ id: 143, topic: "OWASP LLM", correct: "A",
  q: "Which OWASP LLM entry covers manipulating LLM input via crafted prompts to override system instructions?",
  options: { A: "LLM01 — Prompt Injection", B: "LLM02 — Insecure Output", C: "LLM03 — Training Data Poisoning", D: "LLM10 — Model Theft" } },
{ id: 144, topic: "OWASP LLM", correct: "B",
  q: "Which OWASP LLM entry covers LLM output consumed downstream without sanitisation, leading to XSS, SSRF, RCE?",
  options: { A: "LLM01", B: "LLM02 — Insecure Output Handling", C: "LLM06", D: "LLM05" } },

// ===== Module 9 · Privacy =====
{ id: 145, topic: "PII vs PHI", correct: "C",
  q: "Most accurate combination?",
  options: { A: "Name + email = PHI", B: "SSN = PHI only", C: "Name + email + SSN = PII; diagnosis + prescription = PHI", D: "None are PII or PHI" } },
{ id: 146, topic: "De-identification", correct: "A",
  q: "Direct identifiers replaced with token (CUST_8a1c); mapping held under access control. Which technique?",
  options: { A: "Pseudonymisation", B: "Anonymisation", C: "Encryption", D: "Hashing" } },
{ id: 147, topic: "De-identification", correct: "B",
  q: "Irreversibly stripped of direct/indirect identifiers so re-identification is impossible. Which technique?",
  options: { A: "Pseudonymisation", B: "Anonymisation", C: "Tokenisation", D: "Differential privacy" } },
{ id: 148, topic: "De-identification", correct: "C",
  q: "Each record indistinguishable from at least k-1 others on quasi-identifiers. Which property?",
  options: { A: "l-diversity", B: "t-closeness", C: "k-anonymity", D: "Differential privacy" } },
{ id: 149, topic: "De-identification", correct: "D",
  q: "Each equivalence class must have at least l different sensitive-attribute values. Which property?",
  options: { A: "k-anonymity", B: "t-closeness", C: "Differential privacy", D: "l-diversity" } },
{ id: 150, topic: "De-identification", correct: "A",
  q: "Distribution of sensitive attributes within equivalence class close to overall distribution. Which property?",
  options: { A: "t-closeness", B: "k-anonymity", C: "l-diversity", D: "Differential privacy" } },
{ id: 151, topic: "Privacy Tech", correct: "C",
  q: "Calibrated noise added; ε bounds the privacy loss for individuals. Which technique?",
  options: { A: "Pseudonymisation", B: "Tokenisation", C: "Differential privacy", D: "k-anonymity" } },
{ id: 152, topic: "Privacy Tech", correct: "B",
  q: "Compute analytics directly on encrypted data; neither model nor environment sees plaintext. Which technique?",
  options: { A: "Tokenisation", B: "Homomorphic encryption", C: "TLS", D: "AES-256" } },
{ id: 153, topic: "Privacy Tech", correct: "D",
  q: "Banks jointly train a model without revealing individual data via a cryptographic protocol. Which technique?",
  options: { A: "Differential privacy", B: "Pseudonymisation", C: "Tokenisation", D: "Secure Multi-Party Computation" } },
{ id: 154, topic: "Privacy Tech", correct: "A",
  q: "Hospitals train a shared model without centralising patient data; only model updates aggregated. Which approach?",
  options: { A: "Federated learning", B: "Homomorphic encryption", C: "Differential privacy", D: "Pseudonymisation" } },
{ id: 155, topic: "Privacy Paradigms", correct: "B",
  q: "Privacy controls embedded into architecture from earliest design stage. Which principle?",
  options: { A: "Privacy by default", B: "Privacy by design", C: "Data localisation", D: "Privacy by oversight" } },
{ id: 156, topic: "Privacy Paradigms", correct: "C",
  q: "At signup, privacy settings default to most protective without user opt-out. Which principle?",
  options: { A: "Privacy by design", B: "Opt-in consent", C: "Privacy by default", D: "Lawful basis" } },
{ id: 157, topic: "Privacy Paradigms", correct: "A",
  q: "Collect only data strictly necessary for the stated service. Which GDPR principle?",
  options: { A: "Data minimisation", B: "Purpose limitation", C: "Storage limitation", D: "Accuracy" } },
{ id: 158, topic: "Privacy Paradigms", correct: "D",
  q: "Personal data not retained longer than necessary. Which GDPR principle?",
  options: { A: "Data minimisation", B: "Lawfulness", C: "Accuracy", D: "Storage limitation" } },
{ id: 159, topic: "Cryptography", correct: "B",
  q: "Cloud data destroyed by deleting encryption keys; ciphertext unrecoverable while storage reused. Which method?",
  options: { A: "Physical destruction", B: "Cryptographic erasure", C: "Secure wiping", D: "Randomisation" } },
{ id: 160, topic: "Cryptography", correct: "A",
  q: "Deterministic surrogate replaces a sensitive identifier; mapping held in secure vault. Which technique?",
  options: { A: "Tokenisation", B: "Hashing", C: "Encryption", D: "Encoding" } },
{ id: 161, topic: "Privacy Governance", correct: "C",
  q: "Auditable record evaluating privacy risks, mitigations, data handling before AI handles sensitive data. Which activity?",
  options: { A: "Generic risk register", B: "Privacy Risk Identification only", C: "Privacy Impact Assessment (PIA/DPIA)", D: "Algorithmic Impact Assessment" } },
{ id: 162, topic: "Privacy Governance", correct: "D",
  q: "Assessment of a high-risk automated decision system evaluating impact on rights and freedoms. Called...",
  options: { A: "Threat model", B: "RCSA", C: "SOC 2", D: "Algorithmic Impact Assessment" } },
{ id: 163, topic: "Trust & Safety", correct: "C",
  q: "Ambiguous low-confidence flag with no prior history should route to moderator review and T&S escalation. Which tier?",
  options: { A: "T0", B: "T1", C: "T2", D: "T3" } },

// ===== Module 10 · IR/BCP =====
{ id: 164, topic: "IR Phases", correct: "A",
  q: "Building runbooks, on-call, tabletops before incidents. Which IR phase?",
  options: { A: "Preparation", B: "Detection", C: "Containment", D: "Recovery" } },
{ id: 165, topic: "IR Phases", correct: "B",
  q: "Observability flags anomaly; response team paged. Which IR phase?",
  options: { A: "Preparation", B: "Detection & analysis", C: "Containment", D: "Eradication" } },
{ id: 166, topic: "IR Phases", correct: "C",
  q: "Isolating services, blocking accounts, degrading impacted features after detection. Which IR phase?",
  options: { A: "Detection", B: "Preparation", C: "Containment", D: "Recovery" } },
{ id: 167, topic: "IR Phases", correct: "D",
  q: "Replacing vulnerable libraries, hardening configs, removing unsafe paths after containment. Which IR phase?",
  options: { A: "Detection", B: "Containment", C: "Preparation", D: "Eradication" } },
{ id: 168, topic: "IR Phases", correct: "A",
  q: "Restoring service from clean baselines and returning to full production. Which IR phase?",
  options: { A: "Recovery", B: "Detection", C: "Eradication", D: "Preparation" } },
{ id: 169, topic: "IR Phases", correct: "B",
  q: "Blameless retrospective and playbook updates after service restored. Which IR phase?",
  options: { A: "Containment", B: "Lessons learned", C: "Preparation", D: "Eradication" } },
{ id: 170, topic: "IR Metrics", correct: "C",
  q: "Time from first abnormal sign to formal identification. Which metric?",
  options: { A: "MTTR", B: "MTTC", C: "MTTD", D: "MTBF" } },
{ id: 171, topic: "IR Metrics", correct: "B",
  q: "Time from identification to blast radius bounded. Which metric?",
  options: { A: "MTTD", B: "MTTC", C: "MTTR", D: "Dwell time" } },
{ id: 172, topic: "IR Metrics", correct: "A",
  q: "Time from incident start to full restoration. Which metric?",
  options: { A: "MTTR", B: "MTTD", C: "MTTC", D: "MTBF" } },
{ id: 173, topic: "Severity", correct: "B",
  q: "Risk of physical harm with no injury; unsafe AI behaviour observed. Severity?",
  options: { A: "Low", B: "High", C: "Critical", D: "Informational" } },
{ id: 174, topic: "Severity", correct: "A",
  q: "AI failure: customer-impacting, regulatory exposure, press attention. Severity?",
  options: { A: "P1 / Critical", B: "P2 / High", C: "P3 / Medium", D: "P4 / Low" } },
{ id: 175, topic: "Escalation", correct: "C",
  q: "Progressive routing through levels from responders to executives by severity. Called...",
  options: { A: "Communication matrix", B: "Notification strategy", C: "Escalation hierarchy", D: "Regulatory engagement" } },
{ id: 176, topic: "BCP", correct: "D",
  q: "CRO identifies which AI models support core functions and estimates downtime impact to prioritise recovery. Which process?",
  options: { A: "DR planning", B: "Post-incident review", C: "IR lifecycle", D: "Business Impact Analysis" } },
{ id: 177, topic: "BCP Metrics", correct: "A",
  q: "Maximum tolerable downtime before unacceptable consequences. Which metric?",
  options: { A: "RTO", B: "RPO", C: "MTBF", D: "MTTR" } },
{ id: 178, topic: "BCP Metrics", correct: "B",
  q: "Maximum acceptable data loss measured in time. Which metric?",
  options: { A: "RTO", B: "RPO", C: "MTTD", D: "MTTC" } },
{ id: 179, topic: "DR Sites", correct: "C",
  q: "DR site fully synchronised with prod, taking over in minutes. Which type?",
  options: { A: "Cold", B: "Warm", C: "Hot", D: "Mobile" } },
{ id: 180, topic: "DR Sites", correct: "B",
  q: "DR site with hardware and partial replication; needs catch-up before going live. Which type?",
  options: { A: "Cold", B: "Warm", C: "Hot", D: "Active-active" } },
{ id: 181, topic: "DR Sites", correct: "A",
  q: "DR site with hardware and connectivity but minimal data; hours/days to restore from backups. Which type?",
  options: { A: "Cold", B: "Warm", C: "Hot", D: "Active-active" } },
{ id: 182, topic: "Crisis Mgmt", correct: "B",
  q: "Cascading AI failure affecting multiple critical-infrastructure systems. Best response?",
  options: { A: "Shut down all AI permanently", B: "Multi-domain crisis management with dependency mapping, circuit breakers, coordinated response, public dashboards", C: "Treat each independently", D: "Pause until lawyers engaged" } },
{ id: 183, topic: "Recovery", correct: "C",
  q: "Post-fix, running model on live inputs without outputs affecting business; monitoring before re-activation. Which strategy?",
  options: { A: "Big-bang", B: "Canary", C: "Shadow mode", D: "Blue-green" } },
{ id: 184, topic: "Rollout", correct: "A",
  q: "New version exposed to 5% of users; expand if healthy. Which strategy?",
  options: { A: "Canary", B: "Big-bang", C: "Shadow mode", D: "Offline" } },
{ id: 185, topic: "Rollout", correct: "D",
  q: "Two identical environments (blue, green); traffic cut over in one step with rollback. Which strategy?",
  options: { A: "Canary", B: "Big-bang", C: "Shadow mode", D: "Blue-green" } },

// ===== Module 11 · Audit =====
{ id: 186, topic: "Audit Evidence", correct: "D",
  q: "Regulator: examine internal decision logic, explicit assumptions, formal oversight of changes — not accuracy. Which evidence?",
  options: { A: "Performance", B: "Compliance", C: "Model", D: "Algorithm" } },
{ id: 187, topic: "Audit Evidence", correct: "A",
  q: "Auditor: training-data quality, eval-set composition, statistical performance. Which evidence?",
  options: { A: "Performance", B: "Algorithm", C: "Governance", D: "Compliance" } },
{ id: 188, topic: "Audit Evidence", correct: "B",
  q: "Auditor: architecture, training pipeline, reproducibility artefacts. Which evidence?",
  options: { A: "Algorithm", B: "Model", C: "Performance", D: "Operational" } },
{ id: 189, topic: "Audit Evidence", correct: "C",
  q: "Auditor: AI mapping to regulatory/policy requirements — DPIAs, conformity, sign-offs. Which evidence?",
  options: { A: "Algorithm", B: "Model", C: "Compliance", D: "Performance" } },
{ id: 190, topic: "Audit Types", correct: "A",
  q: "Internal team reviews controls against org policies, reporting to leadership. Which audit type?",
  options: { A: "Internal", B: "External", C: "Regulatory", D: "Certification" } },
{ id: 191, topic: "Audit Types", correct: "B",
  q: "Independent third-party firm reviews AI controls and issues opinion suitable for customer assurance. Which audit type?",
  options: { A: "Internal", B: "External / third-party assurance", C: "Regulatory", D: "Pen test" } },
{ id: 192, topic: "Continuous Monitoring", correct: "C",
  q: "Responsible-AI dashboard for production LLM should include which four KPIs?",
  options: { A: "Token cost, latency, uptime, user rating", B: "Cost, churn, NPS, MAU", C: "Drift, fairness, latency, hallucination rate", D: "CTR, conversion, retention, ARPU" } },
{ id: 193, topic: "Red Teaming", correct: "A",
  q: "Offensive-security team simulating adversaries (jailbreaks, injection, exfil, tool abuse). Which team?",
  options: { A: "Red team", B: "Blue team", C: "Purple team", D: "White team" } },
{ id: 194, topic: "Red Teaming", correct: "C",
  q: "Red and blue teams in real time — red attacks, blue defends, both share observations. Which arrangement?",
  options: { A: "Pen test", B: "Bug bounty", C: "Purple team", D: "Tabletop" } },
{ id: 195, topic: "Red Team Coverage", correct: "B",
  q: "Red-team report covers toxicity, narrow PII-from-prompt, refusal robustness. Missing test classes most likely include...",
  options: { A: "Branding and UX", B: "Jailbreak, training-data extraction, tool/agent abuse, indirect prompt injection", C: "Load testing", D: "Spam coverage" } },
{ id: 196, topic: "Documentation", correct: "B",
  q: "Artefact documenting origin, curation, constraints, limitations of data assets — independent of any model. What is this?",
  options: { A: "Model card", B: "Datasheet for datasets", C: "Decision log", D: "Transparency report" } },
{ id: 197, topic: "Documentation", correct: "A",
  q: "Artefact describing model architecture, intended use, factors, evaluation, ethics, limitations, license. What is this?",
  options: { A: "Model card", B: "Datasheet", C: "Decision log", D: "AIBOM" } },
{ id: 198, topic: "Documentation", correct: "C",
  q: "Auditor asks for record of every individual model decision with timestamp, inputs, outputs, version, overrides. What artefact?",
  options: { A: "Model card", B: "Datasheet", C: "Decision log", D: "AIBOM" } },
{ id: 199, topic: "Right to Explanation", correct: "B",
  q: "Regulator requires adverse automated decisions be defensible to applicants/regulators, independent of technique. Which concept?",
  options: { A: "Feature attribution", B: "Right to explanation", C: "User consent", D: "Data localisation" } },
{ id: 200, topic: "Versioning", correct: "C",
  q: "Auditor traces which dataset trained model, when updated, who approved, supporting docs. Which requirement?",
  options: { A: "Access control", B: "Lifecycle reviews", C: "Versioning and traceability", D: "Decommissioning" } },

];
